# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Esmjs < Formula
  desc ""
  homepage "https://github.com/naecoo/esmjs"
  version "0.0.5"

  on_macos do
    url "https://github.com/naecoo/esmjs/releases/download/v0.0.5/esmjs_0.0.5_darwin_all.tar.gz"
    sha256 "02e966d70e605f20d93cfee97ca5217f225ebf2cf4aa389bfd849adaed4cbbeb"

    def install
      bin.install "esmjs"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/naecoo/esmjs/releases/download/v0.0.5/esmjs_0.0.5_linux_arm64.tar.gz"
      sha256 "601b38d8b3b8a42aa43fd2c5757c9d33e576dde4e01939c77a65a374091cfb65"

      def install
        bin.install "esmjs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/naecoo/esmjs/releases/download/v0.0.5/esmjs_0.0.5_linux_amd64.tar.gz"
      sha256 "dc8684d7e86fae65f260c18b80649635094811affeb85ad3ead11d51452358d2"

      def install
        bin.install "esmjs"
      end
    end
  end
end
